[package]
name = "charwiz"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.13", features = ["attributes"] }
clipboard-win = "5.4.0"
rdev = "0.5.3"
rlua = "0.20.1"

[dependencies.windows]
version = "0.59"
features = [
    "Win32_Globalization",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging"
]
