[[actions]]
keys = ["Ctrl", "Shift", "Alt"]
target = "word"
switch_keyboard_layout = true
handler = "convert_char_layout"

[[actions]]
keys = ["Ctrl", "Shift", "MetaLeft"]
target = "selection"
switch_keyboard_layout = true
handler = "convert_char_layout"

[[actions]]
keys = ["Ctrl", "Shift", "KeyZ"]
target = "selection"
handler = "invert_case"

[[actions]]
keys = ["Ctrl", "Alt", "KeyV"]
target = "selection"
keep_selection = true
handler = "to_snake_case"

[[actions]]
keys = ["Ctrl", "Alt", "KeyB"]
target = "selection"
keep_selection = true
handler = "to_pascal_case"

[[actions]]
keys = ["Ctrl", "Alt", "KeyN"]
target = "selection"
keep_selection = true
handler = "to_camel_case"

[[actions]]
keys = ["Ctrl", "Alt", "KeyM"]
target = "selection"
keep_selection = true
handler = "to_kebab_case"
